site_name: ezprez

nav:
    - Home: index.md
    - Quick Start: quick-start.md
    - Slide Object: slide.md
    - Presentation Object: presentation.md
    - Component Objects: components.md

theme: readthedocs

repo_url: https://github.com/Descent098/ezprez

site_description: An object based api for generating web presentations/slideshows

site_author: Kieran Wood
