site_name: ezprez

nav:
    - Home: index.md

theme: readthedocs

repo_url: https://github.com/Descent098/ezprez

site_description: An object based api for generating web presentations

site_author: Kieran Wood
