name: Build api docs

on:
  push:
    branches:
      - master
      - main

jobs:
  build-api-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install .
        python -m pip install --upgrade pdoc3
        python -m pip install --upgrade mkdocs

    - name: Remove source files
      run: rm -rf *

    - name: build html files
      run: |
        python -m pdoc ezspreadsheet --html --force
        mv "html/ezspreadsheet.html" "html/index.html"

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
